"""Made comment as not null.

Revision ID: 406c8ba94e31
Revises: f8c3be69ad12
Create Date: 2026-09-25 16:40:54.928653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406c8ba94e31'
down_revision: Union[str, Sequence[str], None] = 'f8c3be69ad12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
