"""track booking reminders.

Revision ID: e82ee27ac6c8
Revises: c4d9014b4946
Create Date: 2026-09-26 16:22:25.030875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82ee27ac6c8'
down_revision: Union[str, Sequence[str], None] = 'c4d9014b4946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_sent_at')
    # ### end Alembic commands ###
