from enum import StrEnum


class Action(StrEnum):
    profile_update = "profile.update"
    password_change = "password.change"
    users_list = "users.list"
    users_role_change = "users.role.change"
    users_active_change = "users.active.change"
    users_delete = "users.delete"
    events_create = "events.create"
    events_edit = "events.edit"
    events_publish = "events.publish"
    events_complete = "events.complete"
    events_cancel = "events.cancel"
    events_view_own = "events.view_own"
    categories_create = "categories.create"
    tags_create = "tags.create"
    bookings_create = "bookings.create"
    bookings_view = "bookings.view"
    bookings_cancel = "bookings.cancel"
    reviews_create = "reviews.create"
    reviews_reply = "reviews.reply"
    reviews_edit = "reviews.edit"
    reviews_delete = "reviews.delete"
    notifications_view = "notifications.view"
    notifications_update = "notifications.edit"
    audit_logs_view = "audit_logs.view"
